name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
        java-package: jre
    # Old versions of bedrock use old libssl that Ubuntu no longer ships with; need manual install
    - name: (Linux) Install libssl 1.1
      if: runner.os == 'Linux'
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
    - run: npm install
    - run: npm test